import { ThemeConfig, FontOption, ThemeId, FontId } from '../types';

export const THEMES: Record<string, ThemeConfig> = {
  'tech-guide-pro': {
    id: 'tech-guide-pro',
    name: 'Tech Guide Pro (Viral Tutorial)',
    bgClass: 'from-[#eef3f9] via-[#e2ebf6] to-[#d6e3f2]',
    cardBg: '#ffffff',
    primaryGlow: 'rgba(37, 99, 235, 0.12)',
    badgeBg: '#ff4d36',
    badgeText: '#ffffff',
    titleColor: '#0f172a',
    bodyColor: '#475569',
    accentColor: '#ff4d36',
    borderClass: 'border-slate-200/80 shadow-[0_20px_50px_rgba(30,58,138,0.08)]',
    fontFamily: 'font-jakarta',
    footerColor: '#2563eb',
    isDark: false,
    isDottedCanvas: true,
    hasCornerBlobs: true,
  },
  'blueprint-system': {
    id: 'blueprint-system',
    name: 'Blueprint System (Architecture)',
    bgClass: 'from-[#f0f4f9] via-[#e6eef8] to-[#dbe8f6]',
    cardBg: '#ffffff',
    primaryGlow: 'rgba(14, 116, 144, 0.12)',
    badgeBg: 'rgba(2, 132, 199, 0.12)',
    badgeText: '#0284c7',
    titleColor: '#0f172a',
    bodyColor: '#334155',
    accentColor: '#0284c7',
    borderClass: 'border-sky-200 shadow-[0_20px_50px_rgba(2,132,199,0.08)]',
    fontFamily: 'font-jakarta',
    footerColor: '#0284c7',
    isDark: false,
    isDottedCanvas: true,
  },
  'google-gemini-dark': {
    id: 'google-gemini-dark',
    name: 'Google Gemini Dark',
    bgClass: 'from-[#131314] via-[#0e0e11] to-[#08080a]',
    cardBg: '#131314',
    primaryGlow: 'rgba(66, 133, 244, 0.25)',
    badgeBg: 'rgba(66, 133, 244, 0.15)',
    badgeText: '#8ab4f8',
    titleColor: '#e8eaed',
    bodyColor: '#9aa0a6',
    accentColor: '#4285f4',
    borderClass: 'border-[#2d2f31]',
    fontFamily: 'font-jakarta',
    footerColor: '#8ab4f8',
    isDark: true,
    googleAccentBorder: true,
  },
  'google-material-light': {
    id: 'google-material-light',
    name: 'Google Material Light',
    bgClass: 'from-[#ffffff] via-[#f8f9fa] to-[#f1f3f4]',
    cardBg: '#ffffff',
    primaryGlow: 'rgba(26, 115, 232, 0.12)',
    badgeBg: 'rgba(26, 115, 232, 0.1)',
    badgeText: '#1a73e8',
    titleColor: '#202124',
    bodyColor: '#5f6368',
    accentColor: '#1a73e8',
    borderClass: 'border-[#dadce0]',
    fontFamily: 'font-jakarta',
    footerColor: '#1a73e8',
    isDark: false,
    googleAccentBorder: true,
  },
  'cyber-neon': {
    id: 'cyber-neon',
    name: 'Elegant Dark',
    bgClass: 'from-[#0f172a] via-[#090d16] to-[#020617]',
    cardBg: '#0b1120',
    primaryGlow: 'rgba(37, 99, 235, 0.2)',
    badgeBg: 'rgba(59, 130, 246, 0.15)',
    badgeText: '#60a5fa',
    titleColor: '#ffffff',
    bodyColor: '#94a3b8',
    accentColor: '#3b82f6',
    borderClass: 'border-[#1e293b]',
    fontFamily: 'font-jakarta',
    footerColor: '#64748b',
    isDark: true,
  },
  'midnight-slate': {
    id: 'midnight-slate',
    name: 'Midnight Obsidian',
    bgClass: 'from-[#111114] via-[#0d0d10] to-[#050507]',
    cardBg: '#111114',
    primaryGlow: 'rgba(99, 102, 241, 0.15)',
    badgeBg: 'rgba(99, 102, 241, 0.15)',
    badgeText: '#a5b4fc',
    titleColor: '#f8fafc',
    bodyColor: '#94a3b8',
    accentColor: '#6366f1',
    borderClass: 'border-[#1f1f23]',
    fontFamily: 'font-jakarta',
    footerColor: '#64748b',
    isDark: true,
  },
  'editorial-warm': {
    id: 'editorial-warm',
    name: 'Editorial Cream (Light)',
    bgClass: 'from-[#faf8f5] via-[#f5f1eb] to-[#ece5da]',
    cardBg: '#fdfbf7',
    primaryGlow: 'rgba(217, 119, 6, 0.08)',
    badgeBg: 'rgba(180, 83, 9, 0.12)',
    badgeText: '#92400e',
    titleColor: '#1c1917',
    bodyColor: '#44403c',
    accentColor: '#d97706',
    borderClass: 'border-stone-300',
    fontFamily: 'font-jakarta',
    footerColor: '#78716c',
    isDark: false,
  },
  'minimal-paper-light': {
    id: 'minimal-paper-light',
    name: 'Minimal Paper (Light)',
    bgClass: 'from-[#f8fafc] via-[#f1f5f9] to-[#e2e8f0]',
    cardBg: '#ffffff',
    primaryGlow: 'rgba(15, 23, 42, 0.06)',
    badgeBg: 'rgba(15, 23, 42, 0.08)',
    badgeText: '#0f172a',
    titleColor: '#0f172a',
    bodyColor: '#475569',
    accentColor: '#0284c7',
    borderClass: 'border-slate-200',
    fontFamily: 'font-jakarta',
    footerColor: '#0284c7',
    isDark: false,
  },
  'emerald-growth': {
    id: 'emerald-growth',
    name: 'Emerald Growth',
    bgClass: 'from-[#041a14] via-[#02100d] to-[#010806]',
    cardBg: '#051814',
    primaryGlow: 'rgba(16, 185, 129, 0.18)',
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    badgeText: '#6ee7b7',
    titleColor: '#ffffff',
    bodyColor: '#94a3b8',
    accentColor: '#10b981',
    borderClass: 'border-emerald-900/40',
    fontFamily: 'font-jakarta',
    footerColor: '#6ee7b7',
    isDark: true,
  },
  'sunset-radiant': {
    id: 'sunset-radiant',
    name: 'Sunset Radiant',
    bgClass: 'from-[#1c0c16] via-[#12070e] to-[#080206]',
    cardBg: '#160a12',
    primaryGlow: 'rgba(244, 63, 94, 0.18)',
    badgeBg: 'rgba(244, 63, 94, 0.15)',
    badgeText: '#fda4af',
    titleColor: '#ffffff',
    bodyColor: '#cbd5e1',
    accentColor: '#f43f5e',
    borderClass: 'border-rose-900/40',
    fontFamily: 'font-jakarta',
    footerColor: '#f43f5e',
    isDark: true,
  },
  'obsidian-luxe': {
    id: 'obsidian-luxe',
    name: 'Obsidian Gold',
    bgClass: 'from-[#12110e] via-[#0c0b09] to-[#050504]',
    cardBg: '#12100d',
    primaryGlow: 'rgba(245, 158, 11, 0.12)',
    badgeBg: 'rgba(245, 158, 11, 0.15)',
    badgeText: '#fbbf24',
    titleColor: '#fafafa',
    bodyColor: '#a1a1aa',
    accentColor: '#f59e0b',
    borderClass: 'border-amber-900/40',
    fontFamily: 'font-jakarta',
    footerColor: '#71717a',
    isDark: true,
  },
  'electric-purple': {
    id: 'electric-purple',
    name: 'Electric Purple',
    bgClass: 'from-[#170c26] via-[#0d0617] to-[#06020c]',
    cardBg: '#140b22',
    primaryGlow: 'rgba(192, 132, 252, 0.2)',
    badgeBg: 'rgba(168, 85, 247, 0.15)',
    badgeText: '#d8b4fe',
    titleColor: '#ffffff',
    bodyColor: '#cbd5e1',
    accentColor: '#a855f7',
    borderClass: 'border-purple-900/40',
    fontFamily: 'font-jakarta',
    footerColor: '#a855f7',
    isDark: true,
  }
};

export const FONT_OPTIONS: FontOption[] = [
  {
    id: 'jakarta',
    name: 'Plus Jakarta Sans',
    category: 'Modern Clean',
    className: 'font-jakarta',
    sampleText: 'High Impact Clarity',
  },
  {
    id: 'outfit',
    name: 'Outfit',
    category: 'Geometric Tech',
    className: 'font-outfit',
    sampleText: 'Sharp & Distinctive',
  },
  {
    id: 'syne',
    name: 'Syne',
    category: 'Bold Display',
    className: 'font-syne',
    sampleText: 'Artistic & Expressive',
  },
  {
    id: 'space',
    name: 'Space Grotesk',
    category: 'Tech & Future',
    className: 'font-space',
    sampleText: 'Digital Engineering',
  },
  {
    id: 'playfair',
    name: 'Playfair Display',
    category: 'Editorial Serif',
    className: 'font-playfair',
    sampleText: 'Luxury & Elegance',
  },
  {
    id: 'poppins',
    name: 'Poppins',
    category: 'Friendly Rounded',
    className: 'font-poppins',
    sampleText: 'Approachable & Warm',
  },
  {
    id: 'inter',
    name: 'Inter',
    category: 'Neutral Product',
    className: 'font-inter',
    sampleText: 'System Precision',
  },
  {
    id: 'mono',
    name: 'JetBrains Mono',
    category: 'Developer Code',
    className: 'font-mono-jb',
    sampleText: 'Code & Data Focus',
  },
];

export const DEFAULT_THEME_ID: ThemeId = 'google-gemini-dark';
export const DEFAULT_THEME: ThemeConfig = THEMES['google-gemini-dark'];

export const DEFAULT_FONT_ID: FontId = 'jakarta';
export const DEFAULT_FONT: FontOption = FONT_OPTIONS[0];

export function getTheme(themeId?: string | null): ThemeConfig {
  if (themeId && THEMES[themeId]) {
    return THEMES[themeId];
  }
  return DEFAULT_THEME;
}

export function getFont(fontId?: string | null): FontOption {
  if (fontId) {
    const found = FONT_OPTIONS.find((f) => f.id === fontId);
    if (found) return found;
  }
  return DEFAULT_FONT;
}

export const AVAILABLE_ICONS = [
  { id: 'sparkles', label: 'Sparkles', emoji: '✨' },
  { id: 'terminal', label: 'Terminal / CLI', emoji: '💻' },
  { id: 'key', label: 'API Key / Auth', emoji: '🔑' },
  { id: 'download', label: 'Install / Setup', emoji: '📥' },
  { id: 'sliders', label: 'Env / Config', emoji: '⚙️' },
  { id: 'cpu', label: 'AI Model / Chip', emoji: '🧠' },
  { id: 'zap', label: 'Lightning', emoji: '⚡' },
  { id: 'flame', label: 'Fire / Viral', emoji: '🔥' },
  { id: 'rocket', label: 'Rocket Growth', emoji: '🚀' },
  { id: 'lightbulb', label: 'Idea / Tip', emoji: '💡' },
  { id: 'trophy', label: 'Trophy / Success', emoji: '🏆' },
  { id: 'target', label: 'Target / Focus', emoji: '🎯' },
  { id: 'shield', label: 'Security / Shield', emoji: '🛡️' },
  { id: 'chart', label: 'Analytics / Metrics', emoji: '📊' },
  { id: 'diamond', label: 'Diamond / Value', emoji: '💎' },
  { id: 'bookmark', label: 'Save / Bookmark', emoji: '📌' },
  { id: 'star', label: 'Star / Featured', emoji: '⭐' },
  { id: 'code', label: 'Code / Script', emoji: '🧑‍💻' },
  { id: 'globe', label: 'Global / Network', emoji: '🌐' },
];
